version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 10
  reviewers:
  - fussel178
  assignees:
  - fussel178
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
  open-pull-requests-limit: 10
  reviewers:
  - fussel178
  assignees:
  - fussel178
  labels:
  - dependencies
